package cubesolver;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Andrew Campkin @email andrewcampkin@gmail.com
 */
public class CubeFrame extends javax.swing.JFrame {

    /**
     * Creates new form CubeFrame
     */
    public CubeFrame() {
        initComponents();
        cube = new Cube();
        checkScrambled();
        vertices = new Point[56];
        initVertices();
        initVertexList();
        updateCube();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas(){
            @Override
            public void paint(Graphics g)
            {
                super.paint(g);
                g.setColor(Color.RED);
                g.fill3DRect(10, 10, 60, 60, true);
                drawCube(g);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Left");
        jButton1.setToolTipText("Rotate Cube Left");
        jButton1.setName("leftButton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Right");
        jButton2.setToolTipText("Rotate Cube Right");
        jButton2.setName("rightButton");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Up");
        jButton3.setToolTipText("Rotate Cube Up");
        jButton3.setName("upButton");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Down");
        jButton4.setToolTipText("Rotate Cube Down");
        jButton4.setName("downButton");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Scramble");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Not Initialised");
        jLabel1.setToolTipText("Is the cube solved?");
        jLabel1.setName("solveLabel");

        jButton6.setText("Exit");
        jButton6.setToolTipText("Click to exit");
        jButton6.setName("exitButton");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        canvas1.setMinimumSize(new java.awt.Dimension(50, 50));
        canvas1.setPreferredSize(new java.awt.Dimension(553, 335));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton2)
                            .addComponent(jLabel1)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButton4)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton2)
                        .addGap(69, 69, 69)
                        .addComponent(jButton5)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        checkScrambled();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        checkScrambled();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkScrambled();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        checkScrambled();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (cube != null) {
            cube.scramble();
        }
        checkScrambled();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CubeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    // My variables
    private Cube cube;
    private Point[] vertices;
    private int[][] vertexList;

    /**
     * Helper method to check if the cube is solved yet.
     */
    // <editor-fold defaultstate="collapsed" desc="Check Scrambled Method">
    private void checkScrambled() {
        if (cube.isSolved()) {
            jLabel1.setText("Solved");
        } else {
            jLabel1.setText("Not Solved Yet");
        }
    }

    private void updateCube() {
        java.awt.Graphics g = this.getGraphics();
        g.setColor(java.awt.Color.red);
        g.fill3DRect(10, 10, 15, 15, true);
        g.dispose();
    }
    
    private void drawCube(Graphics g){
        
    }

    private void initVertexList(){
        
    }
    
    private void initVertices() {
        vertices[0] = new Point(0, 3);
        vertices[1] = new Point(1, 2);
        vertices[2] = new Point(2, 1);
        vertices[3] = new Point(3, 0);
        vertices[4] = new Point(1, 4);
        vertices[5] = new Point(2, 3);
        vertices[6] = new Point(3, 2);
        vertices[7] = new Point(4, 1);
        vertices[8] = new Point(2, 5);
        vertices[9] = new Point(3, 4);
        vertices[10] = new Point(4, 3);
        vertices[11] = new Point(5, 2);
        vertices[12] = new Point(3, 6);
        vertices[13] = new Point(4, 5);
        vertices[14] = new Point(5, 4);
        vertices[15] = new Point(6, 3);
        vertices[16] = new Point(0, 4);
        vertices[17] = new Point(1, 5);
        vertices[18] = new Point(2, 6);
        vertices[19] = new Point(3, 7);
        vertices[20] = new Point(4, 6);
        vertices[21] = new Point(5, 5);
        vertices[22] = new Point(6, 4);
        vertices[23] = new Point(0, 5);
        vertices[24] = new Point(1, 6);
        vertices[25] = new Point(2, 7);
        vertices[26] = new Point(3, 8);
        vertices[27] = new Point(4, 7);
        vertices[28] = new Point(5, 6);
        vertices[29] = new Point(6, 5);
        vertices[30] = new Point(0, 6);
        vertices[31] = new Point(1, 7);
        vertices[32] = new Point(2, 8);
        vertices[33] = new Point(3, 9);
        vertices[34] = new Point(4, 8);
        vertices[35] = new Point(5, 7);
        vertices[36] = new Point(6, 6);
    }
}
