package cubesolver;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Polygon;

/**
 *
 * @author Andrew Campkin @email andrewcampkin@gmail.com
 */
public class CubeFrame extends javax.swing.JFrame {

    /**
     * Creates new form CubeFrame
     */
    public CubeFrame() {
        initComponents();
        cube = new Cube();
        checkScrambled();
        //56 points to map out the cube
        vertices = new Point[56];
        initVertices();
        //made up of 27 squares
        vertexList = new int[27][4];
        initVertexList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas(){
            @Override
            public void paint(Graphics g)
            {
                super.paint(g);
                drawCube(g);
            }
        };
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cube Solver");

        jButton1.setText("Left");
        jButton1.setToolTipText("Rotate Cube Left");
        jButton1.setName("leftButton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Right");
        jButton2.setToolTipText("Rotate Cube Right");
        jButton2.setName("rightButton");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rotate up");
        jButton3.setToolTipText("Rotate Cube Up");
        jButton3.setName("upButton");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Rotate down");
        jButton4.setToolTipText("Rotate Cube Down");
        jButton4.setName("downButton");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Scramble");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Not Initialised");
        jLabel1.setToolTipText("Is the cube solved?");
        jLabel1.setName("solveLabel");

        jButton6.setText("Exit");
        jButton6.setToolTipText("Click to exit");
        jButton6.setName("exitButton");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        canvas1.setMinimumSize(new java.awt.Dimension(50, 50));
        canvas1.setPreferredSize(new java.awt.Dimension(553, 335));

        jButton7.setText("Rotate up");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Rotate down");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("/");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("/");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("/");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("\\");
            jButton13.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton13ActionPerformed(evt);
                }
            });

            jButton14.setText("\\");
                jButton14.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton14ActionPerformed(evt);
                    }
                });

                jButton15.setText("\\");
                    jButton15.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton15ActionPerformed(evt);
                        }
                    });

                    jButton16.setText("-");
                    jButton16.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton16ActionPerformed(evt);
                        }
                    });

                    jButton17.setText("-");
                    jButton17.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton17ActionPerformed(evt);
                        }
                    });

                    jButton18.setText("-");
                    jButton18.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton18ActionPerformed(evt);
                        }
                    });

                    jButton19.setText("-");
                    jButton19.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton19ActionPerformed(evt);
                        }
                    });

                    jButton20.setText("-");
                    jButton20.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton20ActionPerformed(evt);
                        }
                    });

                    jButton21.setText("-");
                    jButton21.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton21ActionPerformed(evt);
                        }
                    });

                    jButton22.setText("/");
                    jButton22.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton22ActionPerformed(evt);
                        }
                    });

                    jButton23.setText("/");
                    jButton23.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton23ActionPerformed(evt);
                        }
                    });

                    jButton24.setText("/");
                    jButton24.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton24ActionPerformed(evt);
                        }
                    });

                    jButton25.setText("\\");
                        jButton25.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton25ActionPerformed(evt);
                            }
                        });

                        jButton26.setText("\\");
                            jButton26.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton26ActionPerformed(evt);
                                }
                            });

                            jButton27.setText("\\");
                                jButton27.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButton27ActionPerformed(evt);
                                    }
                                });

                                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                getContentPane().setLayout(layout);
                                layout.setHorizontalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jButton13)
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton15)
                                                .addGap(40, 40, 40)
                                                .addComponent(jButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addGap(178, 178, 178)
                                                .addComponent(jButton7))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(58, 58, 58))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton17)
                                                    .addComponent(jButton16)
                                                    .addComponent(jButton18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton8)
                                                .addGap(316, 316, 316))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton19)
                                                        .addComponent(jButton20))
                                                    .addComponent(jButton21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton5)
                                                    .addComponent(jButton2)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jButton9)
                                                    .addComponent(jButton6)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jButton22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton24)
                                        .addGap(57, 57, 57)
                                        .addComponent(jButton25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton27))
                                );
                                layout.setVerticalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(jButton7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(11, 11, 11)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jButton10)
                                                            .addComponent(jButton11)
                                                            .addComponent(jButton12))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jButton13)
                                                            .addComponent(jButton14)
                                                            .addComponent(jButton15))
                                                        .addGap(28, 28, 28)))
                                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(81, 81, 81)
                                                        .addComponent(jButton1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton17)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton18))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(102, 102, 102)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jButton2)
                                                            .addComponent(jButton19))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jButton5)
                                                            .addComponent(jButton20))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel1)
                                                            .addComponent(jButton21))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton9)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton22)
                                            .addComponent(jButton23)
                                            .addComponent(jButton24)
                                            .addComponent(jButton25)
                                            .addComponent(jButton26)
                                            .addComponent(jButton27))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton8)
                                            .addComponent(jButton4))
                                        .addGap(41, 41, 41))
                                );

                                pack();
                            }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        checkScrambled();
        cube.changeCube(1, 1);
        cube.changeCube(1, 2);
        cube.changeCube(1, 3);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        checkScrambled();
        cube.changeCube(0, 4);
        cube.changeCube(0, 5);
        cube.changeCube(0, 6);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkScrambled();
        cube.changeCube(0, 7);
        cube.changeCube(0, 8);
        cube.changeCube(0, 9);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        checkScrambled();
        cube.changeCube(1, 7);
        cube.changeCube(1, 8);
        cube.changeCube(1, 9);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (cube != null) {
            cube.scramble();
        }
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        checkScrambled();
        cube.changeCube(1, 4);
        cube.changeCube(1, 5);
        cube.changeCube(1, 6);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        checkScrambled();
        cube.changeCube(0, 1);
        cube.changeCube(0, 2);
        cube.changeCube(0, 3);
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //reset button
        cube = new Cube();
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        cube.changeCube(1, 1);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        cube.changeCube(1, 2);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        cube.changeCube(1, 3);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        cube.changeCube(1, 4);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        cube.changeCube(1, 5);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        cube.changeCube(1, 6);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        cube.changeCube(1, 7);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        cube.changeCube(1, 8);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        cube.changeCube(1, 9);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        cube.changeCube(0, 7);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        cube.changeCube(0, 8);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        cube.changeCube(0, 9);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        cube.changeCube(0, 4);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        cube.changeCube(0, 5);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        cube.changeCube(0, 6);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        cube.changeCube(0, 1);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        cube.changeCube(0, 2);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        cube.changeCube(0, 3);
        checkScrambled();
        drawCube(canvas1.getGraphics());
    }//GEN-LAST:event_jButton27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CubeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CubeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    // My variables
    private Cube cube;
    private Point[] vertices;
    private int[][] vertexList;

    /**
     * Helper method to check if the cube is solved yet.
     */
    private void checkScrambled() {
        if (cube.isSolved()) {
            jLabel1.setText("Solved");
        } else {
            jLabel1.setText("Not Solved Yet");
        }
    }

    private void drawCube(Graphics g) {
        // here go through the list of vertices drawing a polygon
        for (int i = 0; i < vertexList.length; i++) {//int[] i : vertexList) {
            int[] xVals = new int[vertexList[i].length];
            int[] yVals = new int[vertexList[i].length];
            for (int j = 0; j < 4; j++) {
                xVals[j] = 80 + 30 * (int) vertices[vertexList[i][j]].getX();
                yVals[j] = 20 + 30 * (int) vertices[vertexList[i][j]].getY();
            }
            Polygon p = new Polygon(xVals, yVals, 4);
            int face = 0, square = 0;
            if (i < 9) {
                face = 0;
                square = i;
            } else if (i < 18) {
                face = 2;
                square = i - 9;
            } else {
                face = 1;
                square = i - 18;
            }
            cubeColor c = cube.cubeState[face][square];
            Color nextColor = getColor(c);
            g.setColor(nextColor);
            g.fillPolygon(p);
            g.setColor(Color.BLACK);
            g.drawPolygon(p);
        }
    }

    private void initVertexList() {
        vertexList[0][0] = 0;
        vertexList[0][1] = 1;
        vertexList[0][2] = 5;
        vertexList[0][3] = 4;
        vertexList[1][0] = 1;
        vertexList[1][1] = 2;
        vertexList[1][2] = 6;
        vertexList[1][3] = 5;
        vertexList[2][0] = 2;
        vertexList[2][1] = 3;
        vertexList[2][2] = 7;
        vertexList[2][3] = 6;
        vertexList[3][0] = 4;
        vertexList[3][1] = 5;
        vertexList[3][2] = 9;
        vertexList[3][3] = 8;
        vertexList[4][0] = 5;
        vertexList[4][1] = 6;
        vertexList[4][2] = 10;
        vertexList[4][3] = 9;
        vertexList[5][0] = 6;
        vertexList[5][1] = 7;
        vertexList[5][2] = 11;
        vertexList[5][3] = 10;
        vertexList[6][0] = 8;
        vertexList[6][1] = 9;
        vertexList[6][2] = 13;
        vertexList[6][3] = 12;
        vertexList[7][0] = 9;
        vertexList[7][1] = 10;
        vertexList[7][2] = 14;
        vertexList[7][3] = 13;
        vertexList[8][0] = 10;
        vertexList[8][1] = 11;
        vertexList[8][2] = 15;
        vertexList[8][3] = 14;
        vertexList[9][0] = 0;
        vertexList[9][1] = 4;
        vertexList[9][2] = 17;
        vertexList[9][3] = 16;
        vertexList[10][0] = 4;
        vertexList[10][1] = 8;
        vertexList[10][2] = 18;
        vertexList[10][3] = 17;
        vertexList[11][0] = 8;
        vertexList[11][1] = 12;
        vertexList[11][2] = 19;
        vertexList[11][3] = 18;
        vertexList[12][0] = 16;
        vertexList[12][1] = 17;
        vertexList[12][2] = 24;
        vertexList[12][3] = 23;
        vertexList[13][0] = 17;
        vertexList[13][1] = 18;
        vertexList[13][2] = 25;
        vertexList[13][3] = 24;
        vertexList[14][0] = 18;
        vertexList[14][1] = 19;
        vertexList[14][2] = 26;
        vertexList[14][3] = 25;
        vertexList[15][0] = 23;
        vertexList[15][1] = 24;
        vertexList[15][2] = 31;
        vertexList[15][3] = 30;
        vertexList[16][0] = 24;
        vertexList[16][1] = 25;
        vertexList[16][2] = 32;
        vertexList[16][3] = 31;
        vertexList[17][0] = 25;
        vertexList[17][1] = 26;
        vertexList[17][2] = 33;
        vertexList[17][3] = 32;
        vertexList[18][0] = 12;
        vertexList[18][1] = 13;
        vertexList[18][2] = 20;
        vertexList[18][3] = 19;
        vertexList[19][0] = 13;
        vertexList[19][1] = 14;
        vertexList[19][2] = 21;
        vertexList[19][3] = 20;
        vertexList[20][0] = 14;
        vertexList[20][1] = 15;
        vertexList[20][2] = 22;
        vertexList[20][3] = 21;
        vertexList[21][0] = 19;
        vertexList[21][1] = 20;
        vertexList[21][2] = 27;
        vertexList[21][3] = 26;
        vertexList[22][0] = 20;
        vertexList[22][1] = 21;
        vertexList[22][2] = 28;
        vertexList[22][3] = 27;
        vertexList[23][0] = 21;
        vertexList[23][1] = 22;
        vertexList[23][2] = 29;
        vertexList[23][3] = 28;
        vertexList[24][0] = 26;
        vertexList[24][1] = 27;
        vertexList[24][2] = 34;
        vertexList[24][3] = 33;
        vertexList[25][0] = 27;
        vertexList[25][1] = 28;
        vertexList[25][2] = 35;
        vertexList[25][3] = 34;
        vertexList[26][0] = 28;
        vertexList[26][1] = 29;
        vertexList[26][2] = 36;
        vertexList[26][3] = 35;
    }

    private void initVertices() {
        vertices[0] = new Point(0, 3);
        vertices[1] = new Point(1, 2);
        vertices[2] = new Point(2, 1);
        vertices[3] = new Point(3, 0);
        vertices[4] = new Point(1, 4);
        vertices[5] = new Point(2, 3);
        vertices[6] = new Point(3, 2);
        vertices[7] = new Point(4, 1);
        vertices[8] = new Point(2, 5);
        vertices[9] = new Point(3, 4);
        vertices[10] = new Point(4, 3);
        vertices[11] = new Point(5, 2);
        vertices[12] = new Point(3, 6);
        vertices[13] = new Point(4, 5);
        vertices[14] = new Point(5, 4);
        vertices[15] = new Point(6, 3);
        vertices[16] = new Point(0, 4);
        vertices[17] = new Point(1, 5);
        vertices[18] = new Point(2, 6);
        vertices[19] = new Point(3, 7);
        vertices[20] = new Point(4, 6);
        vertices[21] = new Point(5, 5);
        vertices[22] = new Point(6, 4);
        vertices[23] = new Point(0, 5);
        vertices[24] = new Point(1, 6);
        vertices[25] = new Point(2, 7);
        vertices[26] = new Point(3, 8);
        vertices[27] = new Point(4, 7);
        vertices[28] = new Point(5, 6);
        vertices[29] = new Point(6, 5);
        vertices[30] = new Point(0, 6);
        vertices[31] = new Point(1, 7);
        vertices[32] = new Point(2, 8);
        vertices[33] = new Point(3, 9);
        vertices[34] = new Point(4, 8);
        vertices[35] = new Point(5, 7);
        vertices[36] = new Point(6, 6);
    }

    private Color getColor(cubeColor c) {
        Color newColor;
        switch (c) {
            case WHITE:
                newColor = Color.WHITE;
                break;
            case RED:
                newColor = Color.RED;
                break;
            case BLUE:
                newColor = Color.BLUE;
                break;
            case ORANGE:
                newColor = Color.ORANGE;
                break;
            case GREEN:
                newColor = Color.GREEN;
                break;
            case YELLOW:
                newColor = Color.YELLOW;
                break;
            default:
                newColor = Color.WHITE;
                break;

        }
        return newColor;
    }
}
